# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
  geocoder:
    here_app_id: <%= ENV["GEOCODER_LOOKUP_APP_ID"] %>
    here_app_code: <%= ENV["GEOCODER_LOOKUP_APP_CODE"] %>

development:
  <<: *default
  secret_key_base: eb2734372f74532fc69537a69db9f4c057129ff6b008410ec2b3ee5e8e3eccfe8088ec74d757fb13fcb7d33686c7407e0abf5685aada517c938a0b011be70910
  omniauth:
    developer:
      enabled: true

test:
  <<: *default
  secret_key_base: 748b591febcf6162ab812abb77d5b054cc32e569dfdf732b4df19e98bbc736f997bfb36e9d2634583695c07f0bde7e1637fde0cf879a715a3f4bd5a876b185fd
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
